variables:
  IMAGE_NAME: 'base-image-common:1.0.0'
  DOCKER_REGISTRY: 'docker.4pd.io'

stages:
  - build_and_push_image

build_and_push_image:
  stage: build_and_push_image
  script:
    - sh build-image.sh
    - sh push-image.sh
