FROM docker.4pd.io/meteor/base-image-openjdk8:1.0.0

RUN apk add --repository http://dl-cdn.alpinelinux.org/alpine/v3.10/main python3~=3.7 python3-dev py3-pip && ln -sf python3 /usr/bin/python

WORKDIR /app

CMD ["bash"]
